# Numpy Matrix Operations

In [1]:
import numpy as np

Mathematical & Statistical Operations on Numpy Array

Sum

In [2]:
#We start with Numpy Array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [5]:
#Row wise Sum
npm.sum(axis=1) 

array([280, 240,  60, 200])

In [12]:
#Column Wise Sum
npm.sum(axis=0) # column wise

array([260, 200, 320])

Mean

In [13]:
#Row wise
npm.mean(axis=1)

array([93.33333333, 80.        , 20.        , 66.66666667])

In [14]:
#Column Wise
npm.mean(axis=0)

array([65., 50., 80.])

Replacing elements in Numpy Array

In [15]:
#Consider the array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [16]:
# Replace all elements of numpy array with 50
npm[:,:]=50
npm

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [17]:
# Replace 0,0 position with 500
npm[0,0]=500
npm

array([[500,  50,  50],
       [ 50,  50,  50],
       [ 50,  50,  50],
       [ 50,  50,  50]])

Performing Linear Algebra Operations using NumPy (Matrix Operations)

In [18]:
import numpy as np

Multiplication of 2 Matrices (A of Shape 3x3 multiplied by B of shape 3x2 yields Matrix of shape 3X2)

In [25]:
A=np.matrix([[1,3,2],[4,0,1],[1,0,1]])
A

matrix([[1, 3, 2],
        [4, 0, 1],
        [1, 0, 1]])

In [26]:
B=np.matrix([[1,3],[0,1],[5,2]])
B

matrix([[1, 3],
        [0, 1],
        [5, 2]])

In [27]:
C=A*B
C

matrix([[11, 10],
        [ 9, 14],
        [ 6,  5]])

Dot Product: It is same as Matrix Multiplication

In [29]:
np.dot(A,B)

matrix([[11, 10],
        [ 9, 14],
        [ 6,  5]])

Transpose of Matrix A

In [31]:
A=np.matrix([[1,3,2],[4,0,1],[1,0,1]])
A

matrix([[1, 3, 2],
        [4, 0, 1],
        [1, 0, 1]])

In [30]:
A.T 

matrix([[1, 4, 1],
        [3, 0, 0],
        [2, 1, 1]])

In [3]:
import numpy as np
from numpy import linalg as lng

In [4]:
A = np.array([[6, 1, 1],[4, -2, 5],[2, 8, 7]])
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

Trace of a Matrix The trace of a matrix is the sum of the diagonal elements of the matrix

In [6]:
print("Trace of A:", np.trace(A))

Trace of A: 11


Determinant of Matrix = ad-bc. The determinant of a matrix is a special number that can be calculated from a square matrix. The determinant helps us find the inverse of a matrix, This tells us things about the matrix that are useful in systems of linear equations and calculus

In [7]:
print("Determinant of A:", np.linalg.det(A))

Determinant of A: -306.0


Power of Matrix: Matrix product n times where n is a non negative integer

Eigen Value and Eigen Vector:The eig function returns two tuples: the first one is the eigen values and the second one is eigen vector (a matrix whose columns are the two eigen vectors).

In [64]:
from numpy.linalg import eig

In [65]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [66]:
eigen_val, eigen_vec = eig(A)
eigen_val

array([-0.37228132,  5.37228132])

In [67]:
eigen_vec

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])