In [1]:
timeit 2**128

354 ns ± 5.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [2]:
pwd

'/Users/macbook/Desktop/python/notebooks'

In [3]:
pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [4]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [5]:
import numpy as np

In [6]:
unit_ones = np.ones([2,2], dtype=np.int8)
unit_ones

array([[1, 1],
       [1, 1]], dtype=int8)

In [7]:
unit_ones = np.ones([2,2])
unit_ones

array([[1., 1.],
       [1., 1.]])

In [8]:
string_arr = np.array(["ram", "sham", "jadu"])
string_arr[1] = "good boy"
string_arr

array(['ram', 'good', 'jadu'], dtype='<U4')

In [9]:
string_arr = np.array(["ram", "sham", "jadu"], dtype='<U16')
string_arr[1] = "good boy"
string_arr

array(['ram', 'good boy', 'jadu'], dtype='<U16')

In [10]:
vec1 = np.array([2,4,5])
vec1/2

array([1. , 2. , 2.5])

In [11]:
np.sum(vec1)

11

In [12]:
vec2 = vec1
vec2

array([2, 4, 5])

In [13]:
vec2[0] = 3
vec1

array([3, 4, 5])

In [14]:
vec4 = vec1.copy()
vec4

array([3, 4, 5])

In [15]:
vec4[2] = 10
vec1

array([3, 4, 5])

In [16]:
vec4

array([ 3,  4, 10])

In [17]:
vec1.dtype

dtype('int64')

In [18]:
vec1.dtype = np.float64
vec1

array([1.5e-323, 2.0e-323, 2.5e-323])

In [19]:
zeroarr = np.zeros((2,2,2), dtype=np.float64)
zeroarr

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [20]:
mat1 = np.random.randn(3,3)
mat1

array([[-1.23644585,  0.13234059,  0.79037337],
       [ 0.89743773, -0.66409306, -0.41533962],
       [-1.79066092,  0.08990794, -0.53158174]])

In [21]:
string_arr[string_arr != "ram"]

array(['good boy', 'jadu'], dtype='<U16')

In [22]:
string_arr

array(['ram', 'good boy', 'jadu'], dtype='<U16')

In [23]:
string_arr = np.concatenate((string_arr, np.array(["cycle", "car", "bike"])), axis=0)
string_arr

array(['ram', 'good boy', 'jadu', 'cycle', 'car', 'bike'], dtype='<U16')

In [24]:
from numpy.random import randn
import numpy.linalg as ln

In [25]:
arr1 = np.array(randn(3,3,3) * 10, dtype=np.int64)
arr2 = np.array(randn(3,3,3) * 10, dtype=np.int64)
arr1

array([[[ 14,   3, -19],
        [ -1,   1,  19],
        [ 16, -10,  -1]],

       [[ -5,   6,  18],
        [ -4,  23, -12],
        [ -2,   9,   4]],

       [[-14,   0,   1],
        [ 13,  -4,   6],
        [ -2, -12,  -3]]])

In [26]:
arr2

array([[[-17,   2,  10],
        [-22,  -3, -12],
        [-13, -10,   1]],

       [[  9,  11, -16],
        [ -5,   8, -13],
        [  1,   0,  12]],

       [[  4,  -8,  15],
        [-11,   1,  -6],
        [ -1,   0,  13]]])

In [27]:
arr1 + 100

array([[[114, 103,  81],
        [ 99, 101, 119],
        [116,  90,  99]],

       [[ 95, 106, 118],
        [ 96, 123,  88],
        [ 98, 109, 104]],

       [[ 86, 100, 101],
        [113,  96, 106],
        [ 98,  88,  97]]])

In [28]:
arr1 / 2

array([[[ 7. ,  1.5, -9.5],
        [-0.5,  0.5,  9.5],
        [ 8. , -5. , -0.5]],

       [[-2.5,  3. ,  9. ],
        [-2. , 11.5, -6. ],
        [-1. ,  4.5,  2. ]],

       [[-7. ,  0. ,  0.5],
        [ 6.5, -2. ,  3. ],
        [-1. , -6. , -1.5]]])

In [29]:
arr1 ** 2

array([[[196,   9, 361],
        [  1,   1, 361],
        [256, 100,   1]],

       [[ 25,  36, 324],
        [ 16, 529, 144],
        [  4,  81,  16]],

       [[196,   0,   1],
        [169,  16,  36],
        [  4, 144,   9]]])

In [30]:
arr1 * arr2

array([[[-238,    6, -190],
        [  22,   -3, -228],
        [-208,  100,   -1]],

       [[ -45,   66, -288],
        [  20,  184,  156],
        [  -2,    0,   48]],

       [[ -56,    0,   15],
        [-143,   -4,  -36],
        [   2,    0,  -39]]])

In [31]:
arr1 ** (arr2 / 4)

<ipython-input-31-3b8de1ddd5da>:1: RuntimeWarning: divide by zero encountered in power
  arr1 ** (arr2 / 4)
<ipython-input-31-3b8de1ddd5da>:1: RuntimeWarning: invalid value encountered in power
  arr1 ** (arr2 / 4)


array([[[ 1.34572354e-05,  1.73205081e+00,             nan],
        [            nan,  1.00000000e+00,  1.45793847e-04],
        [ 1.22070312e-04,             nan,             nan]],

       [[            nan,  1.38011711e+02,  9.52598689e-06],
        [            nan,  5.29000000e+02,             nan],
        [            nan,  1.00000000e+00,  6.40000000e+01]],

       [[-1.40000000e+01,             inf,  1.00000000e+00],
        [ 8.64282623e-04,             nan,  6.80413817e-02],
        [            nan,  1.00000000e+00,             nan]]])

In [32]:
arr1.shape

(3, 3, 3)

In [33]:
arr1.transpose()

array([[[ 14,  -5, -14],
        [ -1,  -4,  13],
        [ 16,  -2,  -2]],

       [[  3,   6,   0],
        [  1,  23,  -4],
        [-10,   9, -12]],

       [[-19,  18,   1],
        [ 19, -12,   6],
        [ -1,   4,  -3]]])

In [34]:
arr4 = np.arange(0,8)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [35]:
arr4.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
from sklearn.datasets import load_iris

In [40]:
iris = load_iris().data[:,:]
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [41]:
iris.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [44]:
X = iris.copy()
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [45]:
X_sq = X.T.dot(X)
X_sq

array([[5223.85, 2673.43, 3483.76, 1128.14],
       [2673.43, 1430.4 , 1674.3 ,  531.89],
       [3483.76, 1674.3 , 2582.71,  869.11],
       [1128.14,  531.89,  869.11,  302.33]])

In [46]:
X_sq_inv = ln.inv(X_sq)
X_sq_inv

array([[ 0.05034014, -0.0564344 , -0.04649057,  0.04508845],
       [-0.0564344 ,  0.06736108,  0.04506042, -0.03745986],
       [-0.04649057,  0.04506042,  0.06696879, -0.09831163],
       [ 0.04508845, -0.03745986, -0.09831163,  0.18358105]])

In [47]:
Y = X[:,3]
beta = X_sq_inv.dot(X.T.dot(Y))
beta

array([-1.42108547e-14,  2.48689958e-14,  2.13162821e-14,  1.00000000e+00])

In [49]:
iris_svd = ln.svd(X)
iris_svd[1]

array([95.95991387, 17.76103366,  3.46093093,  1.88482631])

In [50]:
iris_svd[0]

array([[-0.06161685,  0.12961144,  0.0021386 , ..., -0.09343429,
        -0.09573864, -0.08085465],
       [-0.05807094,  0.11101978,  0.07067239, ...,  0.03690405,
        -0.03153954,  0.01309526],
       [-0.05676305,  0.11796647,  0.00434255, ...,  0.03066199,
         0.19531473,  0.13569909],
       ...,
       [-0.0940593 , -0.0498297 , -0.04144001, ...,  0.98181631,
        -0.02194514, -0.00894446],
       [-0.09488961, -0.05610123, -0.21297821, ..., -0.02155617,
         0.94178018, -0.02971961],
       [-0.08847836, -0.0515697 , -0.09575285, ..., -0.0086052 ,
        -0.03021088,  0.9736599 ]])

In [51]:
arr1.tolist()

[[[14, 3, -19], [-1, 1, 19], [16, -10, -1]],
 [[-5, 6, 18], [-4, 23, -12], [-2, 9, 4]],
 [[-14, 0, 1], [13, -4, 6], [-2, -12, -3]]]

In [52]:
arr1.flatten()

array([ 14,   3, -19,  -1,   1,  19,  16, -10,  -1,  -5,   6,  18,  -4,
        23, -12,  -2,   9,   4, -14,   0,   1,  13,  -4,   6,  -2, -12,
        -3])

In [53]:
arr1.sum()

44

In [54]:
arr1.sum(axis=0)

array([[ -5,   9,   0],
       [  8,  20,  13],
       [ 12, -13,   0]])

In [55]:
arr1.cumsum(axis=1)

array([[[ 14,   3, -19],
        [ 13,   4,   0],
        [ 29,  -6,  -1]],

       [[ -5,   6,  18],
        [ -9,  29,   6],
        [-11,  38,  10]],

       [[-14,   0,   1],
        [ -1,  -4,   7],
        [ -3, -16,   4]]])

In [56]:
np.sign(arr1)

array([[[ 1,  1, -1],
        [-1,  1,  1],
        [ 1, -1, -1]],

       [[-1,  1,  1],
        [-1,  1, -1],
        [-1,  1,  1]],

       [[-1,  0,  1],
        [ 1, -1,  1],
        [-1, -1, -1]]])

In [59]:
import pandas as pd
from pandas import Series, DataFrame

In [60]:
ser1 = Series([1,2,3,4])
ser2 = Series(["a", "b", "c", "d"])
ser1

0    1
1    2
2    3
3    4
dtype: int64

In [61]:
ser2

0    a
1    b
2    c
3    d
dtype: object