# Numpy Operations

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

Reshaping a Numpy Array,
Indexing & Slicing a NumPy Array,
Replacing the elements in Numpy Array,
Manipulating NumPy Array,
Performing Mathematical & Statistical Functions using NumPy

In [126]:
import numpy as np

In [127]:
my_list=[1,2,3,4,5]

In [128]:
type(my_list)

list

In [129]:
arr=np.array(my_list)

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [130]:
arr.ndim

1

In [9]:
vector_row = np.array([1,2,3])

In [10]:
vector_row

array([1, 2, 3])

In [11]:
print(vector_row[:2])

[1 2]


In [18]:
print(vector_row[2])

3


In [12]:
vector_column = np.array([[1],[2],[3]])

In [13]:
vector_column

array([[1],
       [2],
       [3]])

In [14]:
vector_column.ndim

2

In [27]:
print(vector_column.size)

3


In [15]:
matrix = np.array([[1,2,3],[4,5,6],[5,9,0],[9,8,10],[5,4,3]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  9,  0],
       [ 9,  8, 10],
       [ 5,  4,  3]])

In [133]:
print(matrix[4:,1:])

[[4 3]]


In [134]:
matrix[4,-2:]

array([4, 3])

In [16]:
print(matrix.shape)

(5, 3)


In [131]:
matrix.size

15

In [19]:
print(matrix[2,1])

9


In [20]:
print(matrix[ : , 1:2])

[[2]
 [5]
 [9]
 [8]
 [4]]


In [132]:
print(matrix[ 2:4 , 0:2 ])

[[5 9]
 [9 8]]


In [22]:
print(matrix[3:4,1:3])

[[ 8 10]]


In [26]:
print(matrix.size)

15


In [31]:
print(np.max(matrix))

10


In [32]:
print(np.min(matrix))

0


In [33]:
print(np.max(matrix,axis=0)) 

[ 9  9 10]


In [56]:
print(np.max(matrix,axis=1))

[ 3  6  9 10  5]


In [36]:
print(np.mean(matrix,axis=1))

[2.         5.         4.66666667 9.         4.        ]


In [135]:
print(matrix.reshape(1,15))

[[ 1  2  3  4  5  6  5  9  0  9  8 10  5  4  3]]


In [139]:
print(matrix.reshape(4,4))

ValueError: cannot reshape array of size 15 into shape (4,4)

In [43]:
matrix_1 = np.array([[1,2,3],[6,5,6],[7,7,9]])

In [44]:
matrix_1

array([[1, 2, 3],
       [6, 5, 6],
       [7, 7, 9]])

In [47]:
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])

In [48]:
matrix_2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [45]:
print(np.add(matrix_1,matrix_2))

[[ 8 10 12]
 [10 10 12]
 [ 8  9 12]]


In [49]:
print(np.subtract(matrix_1,matrix_2))

[[-6 -6 -6]
 [ 2  0  0]
 [ 6  5  6]]


In [50]:
print(matrix_1*matrix_2)

[[ 7 16 27]
 [24 25 36]
 [ 7 14 27]]


In [140]:
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  

In [141]:
x

array([[1, 2],
       [3, 4]])

In [142]:
y

array([[12, 30]])

In [55]:
z=np.concatenate((x,y), axis=0)  
z 

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [145]:
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y.T), axis=1)  
z  

array([[ 1,  3, 12],
       [ 2,  4, 30]])

In [58]:
import numpy as np  
a=np.zeros(5) 
a  

array([0., 0., 0., 0., 0.])

In [59]:
import numpy as np  
a=np.zeros((6,), dtype=int)  
a  

array([0, 0, 0, 0, 0, 0])

In [60]:
import numpy as np  
a=np.zeros((6,2))  
a  

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [61]:
import numpy as np  
a=np.ones((6,1), dtype=int)
a  

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [147]:
import numpy as np  
a = np.array([[1,4,7], [2,5,8],[3,6,9]])  
b=a.flatten()  
b 

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [148]:
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [63]:
b.ndim

1

In [64]:
a.ndim

2

In [65]:
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [154]:
import numpy as np  
a=np.unique([1,2,3,4,3,6,2,4,9,9,0])  
a  

array([0, 1, 2, 3, 4, 6, 9])

In [149]:
import numpy as np  
a = np.array([[1, 1, 0], [1, 1, 0], [2, 3, 4],[5, 9, 8],[2, 3, 4]])  
b=np.unique(a, axis=0)  
b  

array([[1, 1, 0],
       [2, 3, 4],
       [5, 9, 8]])

In [150]:
a

array([[1, 1, 0],
       [1, 1, 0],
       [2, 3, 4],
       [5, 9, 8],
       [2, 3, 4]])

In [155]:
import numpy as np  
a = np.array([[1, 1, 5], [1, 1, 0], [2, 2, 4],[5, 5, 8],[2, 2, 4]])  
a  

array([[1, 1, 5],
       [1, 1, 0],
       [2, 2, 4],
       [5, 5, 8],
       [2, 2, 4]])

In [156]:
b=np.unique(a, axis=1)  
b

array([[1, 5],
       [1, 0],
       [2, 4],
       [5, 8],
       [2, 4]])

In [164]:
import numpy as np  
a=np.random.rand(5,2)  
a 

array([[0.92101796, 0.09501006],
       [0.21260808, 0.00932927],
       [0.62222045, 0.87536072],
       [0.70962059, 0.44149593],
       [0.97609523, 0.32163812]])

In [166]:
import numpy as np  
a=np.random.randint(5,10, size=15)  
a  

array([9, 6, 5, 9, 9, 5, 8, 8, 7, 6, 8, 8, 7, 8, 8])

In [168]:
a=np.random.randint(179,size=(5,3))
a

array([[119,  26,  32],
       [157,  11,   4],
       [116,  55,  78],
       [  3,  14, 107],
       [142,  86,  36]])

In [169]:
import numpy as np  
arr = [0.23, 0.09, 1.2, 1.24, 9.99, 101.01]
r_arr = np.ceil(arr)
r_arr

array([  1.,   1.,   2.,   2.,  10., 102.])

In [76]:
import numpy as np  
arr = [0.23, 0.09, 1.2, 1.24, 9.99]
r_arr = np.floor(arr)
r_arr

array([0., 0., 1., 1., 9.])

In [170]:
import numpy as np  
b = np.array([12, 90, 380, 12, 211]) 
print(np.where(b>12))
a=np.where(b>12)

(array([1, 2, 4], dtype=int64),)


In [82]:
import numpy as np  
npv=np.random.randint(10, size=10)  
a  

array([5, 9, 9, 3, 4, 7, 0, 4, 2, 0])

In [83]:
npm=npv.reshape(2,5)
npm

array([[2, 4, 2, 8, 4],
       [5, 5, 9, 3, 0]])

Indexing & Extracting the element from Numpy Array: For Indexing Count of Row Index Starts from 0 and Count of Column Index also starts from 0

In [84]:
npm[0,3]

8

In [85]:
npm[1,2]

9

In [86]:
#Slicing Numpy Array:Extracting multiple elements from Numpy Array. Here end index is excluded. 

In [87]:
npm[0:1,1:3]

array([[4, 2]])

In [88]:
npm[1:2,0:2]

array([[5, 5]])

In [89]:
#Mathematical & Statistical Operations on Numpy Array

Sum

In [90]:
#We start with Numpy Array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [91]:
npm.sum(axis=1) 

array([280, 240,  60, 200])

In [92]:
npm.sum(axis=0)

array([260, 200, 320])

Mean

In [13]:
#Row wise
npm.mean(axis=1)

array([93.33333333, 80.        , 20.        , 66.66666667])

In [14]:
#Column Wise
npm.mean(axis=0)

array([65., 50., 80.])

Replacing elements in Numpy Array

In [15]:
#Consider the array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [16]:
# Replace all elements of numpy array with 50
npm[:,:]=50
npm

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [17]:
# Replace 0,0 position with 500
npm[0,0]=500
npm

array([[500,  50,  50],
       [ 50,  50,  50],
       [ 50,  50,  50],
       [ 50,  50,  50]])

In [ ]:
Performing Linear Algebra Operations using NumPy (Matrix Operations)

In [18]:
import numpy as np

Multiplication of 2 Matrices (A of Shape 3x3 multiplied by B of shape 3x2 yields Matrix of shape 3X2)

In [174]:
A=np.matrix([[1,3,4],[4,0,2]])
A

matrix([[1, 3, 4],
        [4, 0, 2]])

In [175]:
B=np.matrix([[1,3],[0,1],[5,2]])
B

matrix([[1, 3],
        [0, 1],
        [5, 2]])

In [176]:
C=A*B
C

matrix([[21, 14],
        [14, 16]])

Transpose of Matrix A

In [114]:
A=np.matrix([[5,3,2],[4,0,1],[1,0,1]])
A

matrix([[5, 3, 2],
        [4, 0, 1],
        [1, 0, 1]])

In [115]:
A.T 

matrix([[5, 4, 1],
        [3, 0, 0],
        [2, 1, 1]])

Trace of a Matrix The trace of a matrix is the sum of the diagonal elements of the matrix

In [116]:
print("Trace of A:", np.trace(A))

Trace of A: 6


In [121]:
import numpy as np  
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])   

In [122]:
a

array([[100, 200],
       [ 23,  12]])

In [123]:
b

array([[10, 20],
       [12, 21]])

In [125]:
vdot = np.vdot(a,b)  
print(vdot)   #np.vdot(a,b) = 100 *10 + 200 * 20 + 23 * 12 + 12 * 21 = 5528 

5528


In [177]:
import numpy

print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [178]:
sampleArray = numpy.arange(100, 200, 10)
sampleArray

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [179]:
type(sampleArray)

numpy.ndarray

Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [183]:
a = np.arange(15,56)
print(a[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.

In [184]:
import numpy as np

my_list = [1,2,3,4,5,6]

a = np.array(my_list)
l1=list(a)


In [185]:
type(a)

numpy.ndarray

In [186]:
type(l1)

list

In [187]:
a = [[1, 2], [3, 4]]
x = np.array(a)
b = x.tolist()
print(a == b)

True


In [188]:
a=[1,2,3,4,5]
a1=np.array(a)
a1

b=list(a1)

if b==a:
    print("True")

True


In [189]:
type(a1)

numpy.ndarray

In [190]:
type(b)

list

Write a Python program to get the difference between a given number and 17, if the number is greater than 17 return double the absolute difference.

In [191]:
def dif(a):
    if(a>17):
        b=a-17
        b*=2
        return b 
dif(18)


2

In [ ]:
def diff(a):
    if a <17:
        return((a - 17)*2)
    else:
        return(a - 17)

In [ ]:
def absl(x):
    if abs(x-17) > 17:
        print(abs(x-17)*2)
        
    else:
        pass


In [192]:
def double(x):

    if x-17<=0:
        print(x-17)
    else:
        print((x-17)*2)


In [193]:
double(5)

-12


In [195]:
def dif(n):
    if n>17:
        return (n-17)*2
print(dif(5))


None
