# Numpy Matrix Operations

In [1]:
import numpy as np

In [ ]:
Mathematical & Statistical Operations on Numpy Array

Sum

In [10]:
#We start with Numpy Array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [11]:
#Row wise Sum
npm.sum(axis=1) 

array([280, 240,  60, 200])

In [12]:
#Column Wise Sum
npm.sum(axis=0) # column wise

array([260, 200, 320])

Mean

In [13]:
#Row wise
npm.mean(axis=1)

array([93.33333333, 80.        , 20.        , 66.66666667])

In [14]:
#Column Wise
npm.mean(axis=0)

array([65., 50., 80.])

Replacing elements in Numpy Array

In [15]:
#Consider the array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [16]:
# Replace all elements of numpy array with 50
npm[:,:]=50
npm

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [17]:
# Replace 0,0 position with 500
npm[0,0]=500
npm

array([[500,  50,  50],
       [ 50,  50,  50],
       [ 50,  50,  50],
       [ 50,  50,  50]])

In [ ]:
Performing Linear Algebra Operations using NumPy (Matrix Operations)

In [18]:
import numpy as np

Multiplication of 2 Matrices (A of Shape 3x3 multiplied by B of shape 3x2 yields Matrix of shape 3X2)

In [25]:
A=np.matrix([[1,3,2],[4,0,1],[1,0,1]])
A

matrix([[1, 3, 2],
        [4, 0, 1],
        [1, 0, 1]])

In [26]:
B=np.matrix([[1,3],[0,1],[5,2]])
B

matrix([[1, 3],
        [0, 1],
        [5, 2]])

In [27]:
C=A*B
C

matrix([[11, 10],
        [ 9, 14],
        [ 6,  5]])

In [ ]:
Dot Product: It is same as Matrix Multiplication

In [29]:
np.dot(A,B)

matrix([[11, 10],
        [ 9, 14],
        [ 6,  5]])

Transpose of Matrix A

In [31]:
A=np.matrix([[1,3,2],[4,0,1],[1,0,1]])
A

matrix([[1, 3, 2],
        [4, 0, 1],
        [1, 0, 1]])

In [30]:
A.T 

matrix([[1, 4, 1],
        [3, 0, 0],
        [2, 1, 1]])

Rank of Matrix
The rank of the matrix refers to the number of linearly independent rows or columns in the matrix. ρ(A) is used to denote the rank of matrix A. A matrix is said to be of rank zero when all of its elements are zero.

In [36]:
from numpy import linalg as lng

In [58]:
A = np.array([[6, 1, 1],[4, -2, 5],[2, 8, 7]])
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

Trace of a Matrix The trace of a matrix is the sum of the diagonal elements of the matrix

In [60]:
print("Trace of A:", np.trace(A))

Trace of A: 11
