In [129]:
import numpy as np
import pandas as pd

#### 1. Create the NumPy array with values (1,2,3).
#### Create a second N umpy array with values (4,5,6).
#### Perform simple arithmetic operations on these two
#### N umpy arrays:
#### a. Addition
#### b. Subtraction
#### c. Multiplication
#### d. Division

In [130]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f"a + b {a+b}")
print(f"a - b {a-b}")
print(f"a * b {a*b}")
print(f"a / b {a/b}")

a + b [5 7 9]
a - b [-3 -3 -3]
a * b [ 4 10 18]
a / b [0.25 0.4  0.5 ]


#### 2. Create a Numpy array with values 10 - 90 and set the shape to be 9 * 9

#### a. Extract only the 3rd column from the Numpy array.

#### b. Extract only the 2nd row from the Numpy array

#### c. Extract those cells at the intersection of first two rows and first two columns.

In [131]:
a = np.arange(10, 91)
print(a.shape)

a = a.reshape([9,9])
print(a)

# a.
from_row = 0
to_row = 9
from_col = 2
to_col = 3
print(a[from_row:to_row,from_col:to_col])
# b.
from_row = 1
to_row = 2
from_col = 0
to_col = 9
print(a[from_row:to_row,from_col:to_col].flatten())
# c.
print(a[0:2,0:2])

(81,)
[[10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]
 [82 83 84 85 86 87 88 89 90]]
[[12]
 [21]
 [30]
 [39]
 [48]
 [57]
 [66]
 [75]
 [84]]
[19 20 21 22 23 24 25 26 27]
[[10 11]
 [19 20]]


#### 3. Create a dictionary with 4 items and convert it into panda’s series. Create Dictionary of Pandas series. 
#### Convert above dictionary into data frame Slice last 2 rows from the data frame. 
#### Slice a column from the data frame. 
#### Create dictionary of tuples. Convert it into dataframe.

In [132]:
d = {'month': [1, 4, 7, 10],
    'year': [2012, 2014, 2013, 2014],
    'sale': [55, 40, 84, 31]}
s = pd.Series(d)
print(type(s))
print(s)

df = pd.DataFrame(s).reset_index(level=0)
print(df)

print(df[-2:])

print(df.iloc[:,1:2])

data = {("amg", "masareti"): 'sports', 
        ("rover", "hammer", "thar"): 'suv'}
print(type(data))
df = pd.DataFrame(data.items(), columns=['sports', 'suv'])
print(type(df))
print(df)

<class 'pandas.core.series.Series'>
month               [1, 4, 7, 10]
year     [2012, 2014, 2013, 2014]
sale             [55, 40, 84, 31]
dtype: object
   index                         0
0  month             [1, 4, 7, 10]
1   year  [2012, 2014, 2013, 2014]
2   sale          [55, 40, 84, 31]
  index                         0
1  year  [2012, 2014, 2013, 2014]
2  sale          [55, 40, 84, 31]
                          0
0             [1, 4, 7, 10]
1  [2012, 2014, 2013, 2014]
2          [55, 40, 84, 31]
<class 'dict'>
<class 'pandas.core.frame.DataFrame'>
                  sports     suv
0        (amg, masareti)  sports
1  (rover, hammer, thar)     suv


#### 4. Explain the use of NumPy library along with the Data structures in NumPy.

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.

The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

a = np.arange(6)<br>
a.reshape([3,2])<br>
a = np.array([1, 2, 3, 4, 5, 6])<br>
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])<br>

#### 5. Explain the use of Pandas library along with the Data structures in Pandas.

Pandas is an open-source library that uses for working with relational or labeled data both easily and intuitively. It provides various data structures and operations for manipulating numerical data and time series.<br>
It supports two data structures:
* Series
* Dataframe<br>
list = ['g', 'e', 'e', 'k', 's']<br>
__create series form a char list__<br>
res = pd.Series(list)<br>
__create data frame__<br>
df = pd.DataFrame(list)