In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

t test, chisquare test, one way anova, two way anova

t test is a inferential statistic which is used to determine if there 
is a significant difference between the means of two groups which may 
be related in certain features  

t test - One Sample - to determine difference between the mean of sample 
and population

In [2]:
import scipy.stats as stats 

In [3]:
#class of students
age=[20,23,21,24,15,34,25,23,22,21,20,20,23,21,24,15,34,25,23,22,21,20]

In [4]:
len(age)

22

In [5]:
#Mean of age
ages_mean=np.mean(age)
ages_mean

22.545454545454547

In [6]:
#Lets take sample
sample=np.random.choice(age,10)
sample

array([20, 24, 20, 20, 24, 25, 15, 21, 23, 22])

In [7]:
np.mean(sample)

21.4

In [8]:
#Hypothesis Testing
#Alpha: It’s the probability of making a wrong decision.alpha ranges from 0 to 1

#The p-value is basically the probability of obtaining your sample data IF the 
#null hypothesis (e.g., the average cost of Cairn terriers = $400) were true. 

#If the p-value is low (less than significant value / alpha), the null must go.

In [9]:
#Null Hypothesis: There is no difference between population Mean and Sample mean
#Alternative Hypothesis: There is difference
#alpha value =5%

#p value < 0.05 Reject the null Hypothesis
#p value > 0.05 Fail to reject Null Hypothesis

In [10]:
from scipy.stats import ttest_1samp

In [11]:
ttest,p_value=ttest_1samp(sample,ages_mean)#ages_mean - population mean

In [12]:
ttest

-1.2432327309115274

In [13]:
p_value

0.24519254428485066

In [14]:
#p value > 0.05 so fail to reject null ie means are different

In [15]:
if p_value < 0.05:
    print('Reject Null Hypotesis')
else:
    print('Fail to reject Null Hypothesis')

Fail to reject Null Hypothesis


In [16]:
# One More Example - 1 sample t test

In [17]:
import numpy as np
import math
import scipy.stats as stats
np.random.seed(6)

In [18]:
school_age=stats.poisson.rvs(loc=0,mu=30,size=500)
classA_age=stats.poisson.rvs(loc=0,mu=30,size=100)

In [21]:
#Null Hypothesis: There is no difference between population Mean and Sample mean
#Alternative Hypothesis: There is difference between popultaion Mean and Sample mean
#alpha value =5%

#p value < 0.05 Reject the null Hypothesis
#p value > 0.05 Fail to reject Null Hypothesis

In [22]:
school_age

array([38, 36, 22, 30, 27, 29, 30, 36, 37, 35, 33, 23, 28, 26, 32, 41, 26,
       34, 29, 33, 28, 35, 24, 27, 24, 36, 36, 32, 28, 36, 23, 19, 40, 23,
       24, 26, 44, 30, 33, 32, 22, 25, 37, 31, 36, 23, 26, 24, 32, 31, 41,
       34, 31, 19, 30, 23, 26, 24, 35, 26, 26, 30, 26, 28, 26, 42, 28, 27,
       37, 26, 26, 30, 25, 33, 29, 25, 29, 32, 31, 36, 24, 26, 31, 39, 41,
       22, 36, 22, 25, 27, 35, 23, 33, 26, 34, 33, 36, 39, 31, 29, 33, 36,
       32, 34, 31, 32, 32, 21, 28, 35, 32, 25, 25, 35, 19, 36, 26, 27, 32,
       28, 21, 40, 37, 24, 29, 32, 30, 29, 32, 31, 28, 16, 24, 35, 25, 35,
       33, 33, 35, 42, 38, 41, 29, 21, 31, 22, 38, 27, 46, 26, 39, 27, 24,
       43, 43, 35, 35, 29, 20, 19, 30, 38, 36, 31, 33, 39, 25, 29, 33, 23,
       29, 31, 35, 26, 29, 19, 25, 34, 27, 23, 29, 32, 27, 22, 31, 30, 36,
       26, 36, 33, 34, 31, 27, 17, 25, 43, 27, 26, 38, 28, 31, 26, 30, 31,
       28, 32, 27, 29, 24, 32, 18, 29, 33, 31, 28, 29, 29, 39, 26, 24, 41,
       21, 20, 23, 18, 32

In [23]:
classA_age

array([27, 33, 35, 39, 34, 17, 29, 27, 29, 40, 36, 30, 28, 34, 26, 30, 20,
       32, 39, 22, 27, 32, 32, 29, 43, 26, 41, 32, 26, 36, 29, 27, 32, 28,
       34, 25, 35, 37, 25, 25, 25, 34, 32, 25, 33, 31, 27, 34, 22, 33, 28,
       23, 30, 26, 26, 27, 41, 27, 26, 26, 22, 18, 27, 26, 22, 44, 26, 40,
       40, 31, 26, 25, 31, 26, 34, 38, 41, 28, 40, 41, 25, 28, 26, 25, 35,
       40, 31, 34, 27, 31, 32, 26, 33, 27, 23, 37, 21, 35, 33, 33])

In [24]:
school_age.mean()

30.114

In [25]:
classA_age.mean()

30.32

In [26]:
ttest,p_value=ttest_1samp(classA_age,school_age.mean())

In [27]:
p_value

0.7260933773654308

In [28]:
if p_value < 0.05:
    print('Reject Null Hypotesis')
else:
    print('Fail to reject Null Hypothesis') #ie Null is Valid / True

Fail to reject Null Hypothesis


In [ ]:
# t test - two sample -to determine difference between the mean of sample 
#and population

In [ ]:
#Independent Samples - t test compares the means of two inependent groups 
#in order to determine whether the associated population means are significantly
#different. Independent Sample t test is a parametric test. this test is also 
#known as independent t test  

In [13]:
#Null Hypothesis: There is no difference between two Independent Sample Means
#Alternative Hypothesis: There is difference between two Independent Sample Means
#alpha value =5%

#p value < 0.05 Reject the null Hypothesis
#p value > 0.05 Fail to reject Null Hypothesis

In [49]:
np.random.seed(12)
classB_age=stats.poisson.rvs(loc=0,mu=33,size=100)

In [50]:
classB_age

array([26, 29, 42, 47, 29, 34, 38, 38, 26, 30, 32, 29, 37, 31, 32, 32, 32,
       23, 35, 29, 21, 32, 34, 25, 35, 33, 41, 35, 33, 28, 23, 35, 45, 35,
       30, 47, 45, 36, 31, 35, 30, 27, 31, 41, 32, 33, 38, 27, 38, 25, 25,
       29, 36, 30, 27, 23, 42, 30, 33, 31, 35, 26, 35, 30, 35, 37, 28, 35,
       31, 37, 32, 38, 35, 33, 33, 26, 37, 24, 33, 28, 34, 36, 31, 30, 36,
       28, 38, 35, 34, 39, 42, 25, 23, 31, 24, 33, 33, 31, 39, 35])

In [51]:
#Variance of Class B
classB_age.mean()

32.63

In [53]:
#Variance of Class A --> Variance are Unequal
classA_age.var()

31.429899999999996

In [ ]:
#Variance of Class B -- Variance are unequal
classB_age.var()

In [54]:
ttest,p_value=stats.ttest_ind(classA_age,classB_age,equal_var=False)

In [55]:
ttest

-2.724848131630769

In [56]:
p_value

0.007009572730242513

In [58]:
if p_value < 0.05:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis')

Reject Null Hypothesis


In [59]:
# Paired t test
#when you want to check for how different samples from the same group are you can go for paired t test

In [13]:
#Null Hypothesis: There is no difference between two Dependent Sample Means 
#(Before & After)
#Alternative Hypothesis: There is difference between two Dependent Sample Means
#alpha value =5%

#p value < 0.05 Reject the null Hypothesis
#p value > 0.05 Fail to reject Null Hypothesis

In [60]:
#Weight 1 at time t, weight 2 at time t+t1
weight1=[50,65,70,80,85,55,65,58,77,74]
weight2=weight1+stats.norm.rvs(scale=5,loc=1.25,size=10)

In [61]:
weight1

[50, 65, 70, 80, 85, 55, 65, 58, 77, 74]

In [62]:
weight2

array([49.2983976 , 55.4793778 , 64.77658126, 78.41889653, 83.66145395,
       54.27060846, 63.23152377, 61.08696446, 73.45494093, 67.27351639])

In [63]:
weight_df=pd.DataFrame({'weight10':np.array(weight1),
                      'weight20':np.array(weight2),
                      'weight_change':np.array(weight2)-np.array(weight1)})
weight_df               

weight10   weight20  weight_change
0        50  49.298398      -0.701602
1        65  55.479378      -9.520622
2        70  64.776581      -5.223419
3        80  78.418897      -1.581103
4        85  83.661454      -1.338546
5        55  54.270608      -0.729392
6        65  63.231524      -1.768476
7        58  61.086964       3.086964
8        77  73.454941      -3.545059
9        74  67.273516      -6.726484

In [64]:
ttest,p_value=stats.ttest_rel(weight1,weight2)

In [65]:
p_value

0.034947379954319714

In [66]:
if p_value < 0.05:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis')

Reject Null Hypothesis
