# Introduction to NumPy arrays
NumPy (Numerical Python) is an essential library for working with dimensional arrays (matrices and vectors). Because NumPy has optimizations it is usually much faster than working with Python when processing data.

With an activated virtual environment, install the library:

```
$ pip install numpy
```

In [1]:
import numpy as np

Arrays are homogenous, that is, its items must be of the same type (unlike a Python list)

## Create arrays with lists

In [2]:
# single dimension arrays

array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [4]:
# two dimensions

array = np.array([[1,2],[2,2]])
print(array.shape)
array

(2, 2)


array([[1, 2],
       [2, 2]])

## Create arrays with built-in functions

In [5]:
# 2x2 array with random floats of 0 to 1
np.random.rand(2,2)

array([[0.96463843, 0.26728043],
       [0.71190205, 0.10982393]])

In [6]:
# fill out the 3x4 array with the number 7
np.full((3,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [7]:
# using the number 1 is so common that `ones` is a function!
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# a simple sequence from 0 to 4
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [9]:
# a sequence with three steps from 0 to 27
np.arange(0, 27, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])