In [4]:
%pip install openapi
%pip install catboost

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


### still you may need to install from your terminal and then restart the jupyter
pip install openai

In [6]:
import openai
openai.api_key = "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"

In [7]:
# method to call chatgpt and get the response
def askChatGPT(question, engine="text-davinci-003", max_tokens=240):
    completion = openai.Completion.create(engine=engine, prompt=question, max_tokens=max_tokens)
    return completion.choices[0]['text']

In [8]:
# a generate test with simple question
response = askChatGPT("What is pandas library?", max_tokens=1000)
print(response)



Pandas is a data analysis and manipulation library written for Python. It provides data structures and operations for manipulating numerical tables and time series. It is used for data preparation and analysis, and offers integration with other Python libraries and packages, including NumPy, SciPy, and Matplotlib.


In [9]:
response = askChatGPT("what are some common pandas use cases?")
print(response)



1. Data Analysis and Manipulation: Pandas is an incredibly powerful tool to help you inspect, analyze and clean dirty data. It has powerful data wrangling and transformations capabilities to make working with messy datasets a breeze.

2. Data Visualization: Pandas enables you to quickly create visualizations from your data set with a few lines of code. This can be a great way to iteratively explore and present results of your analysis and to quickly identify trends in the data.

3. Time Series: Pandas can be used to handle, analyze and visualize time series data. This is important when dealing with financial data, sensor data, or other similar data types which have timestamp components.

4. Database Operations: Pandas also provides a library of tools which facilitate integration with databases and SQL. This opens up many opportunities for efficient data manipulation and complex analysis.


In [10]:
response = askChatGPT("what are the most common deep learning librarires?")
print(response)



1. TensorFlow
2. Keras
3. PyTorch
4. MXNet
5. Scikit-learn
6. Theano
7. Caffe
8. CNTK
9. Torch
10. DLib


In [11]:
response = askChatGPT("what is deep neural network?", max_tokens=1000)
print(response)



A deep neural network (DNN) is an artificial neural network (ANN) with multiple layers between the input and output layers. It is a power form of machine learning algorithm known as artificial intelligence (AI). Deep learning is a subset of machine learning where neural network architectures such as deep neural networks, deep belief networks, and recurrent neural networks are used to perform complex tasks such as object classification, AI game playing, and language modelling.


### Features engineering

In [12]:
response = askChatGPT("give some ideas of feature transformations that can improve model performance?", max_tokens=1000)
print(response)



1. Eigenvalue Decomposition: A transformation that extracts meaningful information by eliminating redundant variables and mapping noisy data to the important components.

2. Principal Component Analysis (PCA): It is a transformation that reduces the feature space by projecting the data onto lower-dimensional subspace while preserving the most important variables.

3. Ordinal Encoding: Transformation of categorical variables into an ordered array.

4. One Hot Encoding: Transforming categorical to numerical by creating dummy variables.

5. Binarization: Transform continuous variables into binary decision variables by setting an optimal threshold.

6. Embeddings: Mapping high dimensional variables into lower dimensional space.

7. Interactions: Generating new features by multiplying the values of two or more existing features.

8. Feature Aggregation: Aggregating features from different data sources to enable better learning from the data.


In [25]:
response = askChatGPT("Write an example numpay code using mean, std etc that performs data transformation?", max_tokens=1000)
print(response)



import numpy as np

# Create an array
arr = np.arange(16).reshape(4,4)
print(arr)

# Calculate the mean of the array
mean_arr = np.mean(arr) 
print(mean_arr)

# Calculate the standard deviation of the array
std_arr = np.std(arr) 
print(std_arr)

# Normalize the array
norm_arr = (arr - mean_arr) / std_arr
print(norm_arr)


In [26]:
import numpy as np

# Create an array
arr = np.arange(16).reshape(4,4)
print(arr)

# Calculate the mean of the array
mean_arr = np.mean(arr) 
print(mean_arr)

# Calculate the standard deviation of the array
std_arr = np.std(arr) 
print(std_arr)

# Normalize the array
z_score = (arr - mean_arr) / std_arr
print(z_score)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7.5
4.6097722286464435
[[-1.62697843 -1.41004798 -1.19311752 -0.97618706]
 [-0.7592566  -0.54232614 -0.32539569 -0.10846523]
 [ 0.10846523  0.32539569  0.54232614  0.7592566 ]
 [ 0.97618706  1.19311752  1.41004798  1.62697843]]


In [27]:
response = askChatGPT("Write example python code that perform data normalization on fake data", max_tokens=1000)
print(response)



# Create fake data
data = [15, 18, 2, 36, 12, 78, 5, 6, 9]

# Calculate summary statistics
max_val = max(data)
min_val = min(data)
range_val = max_val - min_val

# Normalize data
normalized_data = []
for x in data: 
  normalized_data.append((x - min_val)/range_val)

# Print normalized data
print(normalized_data) 
# Output: [0.0, 0.2, 0.0, 1.0, 0.1, 1.0, 0.03, 0.04, 0.05]


In [28]:
response = askChatGPT("How do I select a time series model?", max_tokens=1000)
print(response)



Selecting a time series model depends on the type of data available and the forecasting objectives. Factors to consider when selecting a model include data frequency, stationarity or trend, seasonality, and autocorrelation. For example, if the data has multiple seasonal cycles, an autoregressive integrated moving average (ARIMA) model may be a good choice, whereas a random walk model is better for short-term forecasting. Other models to consider include vector autoregression, exponential smoothing, and state space models.


### generating synthetic data

In [29]:
response = askChatGPT("Write example code that generates synthetic healthcare readmission data stored in a dataframe", max_tokens=1000)
print(response)



import pandas as pd 
import numpy as np

# generating patient ids 
patient_ids = np.random.randint(1,10, size=5)
# generating readmission status (boolean)
readmission_status = np.random.choice([True, False], 5)
# generate readmission severity (1 - 5)
readmission_severity = np.random.randint(1,6, size=5)

data = {'Patient_ID': patient_ids ,
        'Readmission_Status': readmission_status,
        'Readmission_Severity': readmission_severity }

df = pd.DataFrame(data)
print(df)


In [31]:
import pandas as pd 
import numpy as np

# generating patient ids 
patient_ids = np.random.randint(1,10, size=5)
# generating readmission status (boolean)
readmission_status = np.random.choice([True, False], 5)
# generate readmission severity (1 - 5)
readmission_severity = np.random.randint(1,6, size=5)

data = {'Patient_ID': patient_ids ,
        'Readmission_Status': readmission_status,
        'Readmission_Severity': readmission_severity }

df = pd.DataFrame(data)
print(df)

   Patient_ID  Readmission_Status  Readmission_Severity
0           3               False                     2
1           2               False                     5
2           6               False                     2
3           9                True                     4
4           2                True                     5


In [32]:
response = askChatGPT("Write example code that generates synthetic healthcare readmission data stored in a dataframe. From this write code that builds a catboost model that predicts readmission outcomes. Also write code to calculate and print performance.", max_tokens=1000)
print(response)



#importing libraries 
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier

#generating synthetic readmission data
np.random.seed(123)
data = {
    'age': np.random.randint(18,90,500),
    'gender': np.random.choice(['male','female'],500),
    'medication': np.random.choice(['yes','no'], 500),
    'readmission': np.random.choice(['yes','no'], 500)
    }
df = pd.DataFrame(data)

#building catboost model
X = df[['age','gender','medication']]
y = df['readmission']
model = CatBoostClassifier()
model.fit(X,y)

#calculating & printing performance
predictions = model.predict(X)
accuracy = sum(predictions == y)/len(y)
print('Model accuracy: ', accuracy)


In [54]:
# after some rectification of the chatgpt code
#importing libraries 
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier

def map_bool_to_int(x):
    if x == 'yes' or x == 'male':
        return 1
    elif x == 'no' or x == 'female':
        return 0

#generating synthetic readmission data
np.random.seed(123)
print(map(map_bool_to_int, np.random.choice(['male','female'],500)))
data = {
    'age': np.random.randint(18,90,500),
    'gender': map(map_bool_to_int, np.random.choice(['male','female'],500)),
    'medication': map(map_bool_to_int, np.random.choice(['yes','no'], 500)),
    'readmission': map(map_bool_to_int, np.random.choice(['yes','no'], 500))
    }
df = pd.DataFrame(data)

#building catboost model
X = df[['age','gender','medication']]
y = df['readmission']
model = CatBoostClassifier()
model.fit(X,y)

#calculating & printing performance
predictions = model.predict(X)
accuracy = sum(predictions == y)/len(y)
print('Model accuracy: ', accuracy)

Learning rate set to 0.007663
0:	learn: 0.6927425	total: 61.5ms	remaining: 1m 1s
1:	learn: 0.6922819	total: 62.4ms	remaining: 31.1s
2:	learn: 0.6918840	total: 63.1ms	remaining: 21s
3:	learn: 0.6914903	total: 63.6ms	remaining: 15.8s
4:	learn: 0.6911493	total: 64ms	remaining: 12.7s
5:	learn: 0.6907643	total: 64.6ms	remaining: 10.7s
6:	learn: 0.6907081	total: 65ms	remaining: 9.23s
7:	learn: 0.6903378	total: 65.8ms	remaining: 8.15s
8:	learn: 0.6902577	total: 66.1ms	remaining: 7.28s
9:	learn: 0.6898219	total: 66.6ms	remaining: 6.59s
10:	learn: 0.6894615	total: 67ms	remaining: 6.03s
11:	learn: 0.6890978	total: 67.6ms	remaining: 5.56s
12:	learn: 0.6887073	total: 68ms	remaining: 5.17s
13:	learn: 0.6885319	total: 68.6ms	remaining: 4.83s
14:	learn: 0.6884011	total: 69ms	remaining: 4.53s
15:	learn: 0.6881821	total: 70.6ms	remaining: 4.34s
16:	learn: 0.6879056	total: 71ms	remaining: 4.11s
17:	learn: 0.6875446	total: 71.5ms	remaining: 3.9s
18:	learn: 0.6871716	total: 71.9ms	remaining: 3.71s
19:	lea

In [55]:
response = askChatGPT("Write example python code that generates synthetic transaction data stored in a dataframe", max_tokens=1000)
print(response)



import pandas as pd
import numpy as np

# Create empty dataframe
df = pd.DataFrame()

# Add columns
df['CustomerName'] = ["John Doe", "Jane Doe", "Joseph Doe"]
df['Amount'] = np.random.randint(20, 200, size=(3,))
df['Category'] = ['Groceries', 'Travel', 'Food']
df['Transaction Date'] = ['05/01/20', '06/01/20','07/01/20']

# Print the dataframe
print(df)


In [56]:
import pandas as pd
import numpy as np

# Create empty dataframe
df = pd.DataFrame()

# Add columns
df['CustomerName'] = ["John Doe", "Jane Doe", "Joseph Doe"]
df['Amount'] = np.random.randint(20, 200, size=(3,))
df['Category'] = ['Groceries', 'Travel', 'Food']
df['Transaction Date'] = ['05/01/20', '06/01/20','07/01/20']

# Print the dataframe
print(df)

  CustomerName  Amount   Category Transaction Date
0     John Doe     114  Groceries         05/01/20
1     Jane Doe     113     Travel         06/01/20
2   Joseph Doe     124       Food         07/01/20


In [57]:
response = askChatGPT("Write example python code that generates synthetic transaction data stored in a dataframe. Includes customer ID, CustomerName, Amount, Category, Age, Gender, and zip code", max_tokens=1000)
print(response)



import pandas as pd
import random

# generate customerIds
customerIds = [random.randint(1000, 10000) for x in range(10)]

# generate names
names = ["John", "Sara", "Mathew", "Graham", "Kris", "Chris", "Karen", "Olivia",
         "Jack", "Emily"]

# generate amounts
amounts = [random.randint(100, 2000) for x in range(10)]

# generate categories
categories = ["Grocery", "Home Improvement",
              "Electronics", "Furniture", "Gas", "Travel", "Clothing", "Kids"]

# generate age
ages = [random.randint(18, 70) for x in range(10)]

# generate gender
gender = ["M", "F"]

# generate zipcode
zipCodes = [random.randint(10001, 11001) for x in range(10)]

# create dictionary
d = { "customerId": customerIds,
      "CustomerName": names,
      "Amount": amounts,
      "Category": categories,
      "Age": ages,
      "Gender": gender,
      "ZipCode": zipCodes
    }

# create dataframe
df = pd.DataFrame(data=d)

# print df
print(df)


In [68]:
# running after some minor correction of code
import pandas as pd
import random

# generate customerIds
customerIds = [random.randint(1000, 10000) for x in range(10)]

# generate names
names = ["John", "Sara", "Mathew", "Graham", "Kris", "Chris", "Karen", "Olivia",
         "Jack", "Emily"]

# generate amounts
amounts = [random.randint(100, 2000) for x in range(10)]

# generate categories
categories = ["Grocery", "Home Improvement",
              "Electronics", "Furniture", "Gas", "Travel", "Clothing", "Kids", "Books", "Pens"]

# generate age
ages = [random.randint(18, 70) for x in range(10)]

# generate gender
gender = np.random.choice(["M", "F"], 10)

# generate zipcode
zipCodes = [random.randint(10001, 11001) for x in range(10)]
print(len(names), len(amounts), len(categories), len(ages), len(gender), len(zipCodes))
# create dictionary
d = { "customerId": customerIds,
      "CustomerName": names,
      "Amount": amounts,
      "Category": categories,
      "Age": ages,
      "Gender": gender,
      "ZipCode": zipCodes
    }

# create dataframe
df = pd.DataFrame(data=d)

# print df
print(df)

10 10 10 10 10 10
   customerId CustomerName  Amount          Category  Age Gender  ZipCode
0        8675         John     728           Grocery   50      F    10729
1        3061         Sara    1701  Home Improvement   68      F    10845
2        2122       Mathew     457       Electronics   32      F    10939
3        2807       Graham     710         Furniture   64      M    10796
4        1879         Kris    1695               Gas   41      M    10189
5        6179        Chris     942            Travel   51      M    10715
6        7309        Karen     422          Clothing   41      M    10088
7        9891       Olivia    1087              Kids   22      M    10133
8        4543         Jack    1440             Books   31      M    10331
9        4300        Emily     691              Pens   59      F    10730


In [69]:
response = askChatGPT("List some good public datasets", max_tokens=1000)
print(response)



1. National Center for Education Statistics: Data on K-12 education, college enrollment, and more
2. Bureau of Labor Statistics: Labor force statistics from the U.S. government
3. DATA.GOV: US government data, from air quality to consumer spending
4. Worldbank Open Data: Data about poverty, health, and the economy
5. Kaggle Datasets: Data resources for data science and machine learning
6. OpenStreetMap: Free geographic data from around the world
7. Eurostat: Statistical data from the European Union
8. Commonwealth Electoral Roll: Electoral roll data from Australia since 1902
9. Humanitarian Data Exchange: Data from partner organizations around the world
10. Global Financial Data: Financial market and macroeconomic data


In [70]:
response = askChatGPT("What are some emergning machine learning use-cases in healthcare?", max_tokens=1000)
print(response)



1. Automated medical image analysis: Automated medical image analysis is a powerful tool for tasks like early detection of tumors and cancer. Machine learning models can detect and analyze abnormal cells in a data set, like MRI scans and CT scans, with remarkable accuracy and precision.

2. Disease forecasting and prevention: Machine learning models can be used to analyze large amounts of medical data to identify patterns in medical history, lifestyle habits, and environmental factors that can help predict the risk of certain diseases. This data can be used to help prevent diseases through personalized care and treatments.

3. Risk classification and stratification: Machine learning techniques can be used to build models that help classify different kinds of patients according to their risk levels. This can help health care professionals to personalize the treatments they offer based on a patient’s risk of developing a certain condition.

4. Clinical decision support system: Machine 

In [71]:
response = askChatGPT("Write a supervisor machine learning example code", max_tokens=1000)
print(response)



from sklearn.ensemble import RandomForestClassifier

#Load data into a variable
X_train, y_train, X_test, y_test = get_data()

#Initialize RandomForestClassifier
clf = RandomForestClassifier(random_state=0)

#Fit the model
clf.fit(X_train, y_train)

#Make predictions
y_pred = clf.predict(X_test)

#Evaluate accuracy of model
accuracy = accuracy_score(y_test, y_pred)

#Use supervised learning techniques to get further insights into the data
#Continuously measure performance
clf.score(X_test, y_test)

#Identifying feature importance
f_importance = list(zip(X_train, clf.feature_importances_))

#Make hyperparameter optimization to find best parameters
clf.best_estimator_


In [74]:
# after correction
from sklearn.ensemble import RandomForestClassifier

#Load data into a variable
X_train, y_train, X_test, y_test = get_data()

#Initialize RandomForestClassifier
clf = RandomForestClassifier(random_state=0)

#Fit the model
clf.fit(X_train, y_train)

#Make predictions
y_pred = clf.predict(X_test)

#Evaluate accuracy of model
accuracy = accuracy_score(y_test, y_pred)

#Use supervised learning techniques to get further insights into the data
#Continuously measure performance
clf.score(X_test, y_test)

#Identifying feature importance
f_importance = list(zip(X_train, clf.feature_importances_))

#Make hyperparameter optimization to find best parameters
clf.best_estimator_

ImportError: cannot import name 'get_data' from 'sklearn.datasets' (/Users/Admin/opt/anaconda3/lib/python3.9/site-packages/sklearn/datasets/__init__.py)