In [1]:
%pip install openapi
%pip install catboost

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


### still you may need to install from your terminal and then restart the jupyter
pip install openai

In [2]:
import openai
openai.api_key = "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"

In [3]:
# method to call chatgpt and get the response
def askChatGPT(question, engine="text-davinci-003", max_tokens=240):
    completion = openai.Completion.create(engine=engine, prompt=question, max_tokens=max_tokens)
    return completion.choices[0]['text']

In [4]:
# a generate test with simple question
response = askChatGPT("What is pandas library?", max_tokens=1000)
print(response)



Pandas is a library for Python designed to provide fast and flexible data analysis tools for working with structured data. Pandas provides a data-oriented programming language for interacting with relational, tabular, and multidimensional data. The library is capable of ingesting CSV, JSON, and SQL databases, and gives users the ability to filter, manipulate, and visualize data quickly and easily.


In [5]:
response = askChatGPT("what are some common pandas use cases?")
print(response)



1. Manipulating and analyzing data sets
2. Cleansing and transforming data
3. Visualizing data with plotting and charting tools
4. Calculating rolling statistics, such as moving averages
5. Merging, joining, and concatenating data sets
6. Reshaping and pivoting data sets
7. Time series analysis (e.g. seasonality and trend analysis)
8. Analyzing experimental and observational data for scientific studies.


In [6]:
response = askChatGPT("what are the most common deep learning librarires?")
print(response)



1. TensorFlow
2. PyTorch
3. Keras
4. Caffe
5. Theano
6. Scikit-Learn
7. MXNet
8. CNTK
9. Deeplearning4j
10. Torch


In [7]:
response = askChatGPT("what is deep neural network?", max_tokens=1000)
print(response)



A deep neural network is an artificial neural network (ANN) with multiple layers between the input and output layers. It can learn features and tasks that a single-layer or shallow neural network cannot. Deep neural networks are used in a variety of applications, including natural language processing, computer vision, and speech recognition.


### Features engineering

In [8]:
response = askChatGPT("give some ideas of feature transformations that can improve model performance?", max_tokens=1000)
print(response)



1. Polynomial Transformation: Use polynomial features to add more complexity to the model.

2. Logarithmic Transformation: Transform numerical data into the logarithmic scale to reduce the effect of outliers and improve the predictive performance of your model.

3. Yeojohnson transformation: Use the Yeojohnson transformation to help deal with both normal and skewed distributions in your data.

4. Standard Scaler: Use a standard scaler to normalize data for linear models and clearly identify influential points in datasets.

5. One-Hot Encoding: Transform categorical data into separate binary variables, in order to make it interpretable by machine learning algorithms.

6. Binning: Discretization of continuous data, i.e grouping of values into bins to improve the interpretability and accuracy of certain models.


In [9]:
response = askChatGPT("Write an example numpay code using mean, std etc that performs data transformation?", max_tokens=1000)
print(response)



#import the necessary libraries
import numpy as np

#Create a normal distribution
normal_distr = np.random.normal(10, 5, 500)

#Transform the distribution 
scaled_distr = normal_distr*0.7 + 0.5 

#Calculate the mean and standard deviation
mean = np.mean(scaled_distr)
std = np.std(scaled_distr)

#Print the mean and standard deviation
print("Mean after transformation is: {}".format(mean)) 
print("Standard deviation after transformation is: {}".format(std))


In [10]:
import numpy as np

# Create an array
arr = np.arange(16).reshape(4,4)
print(arr)

# Calculate the mean of the array
mean_arr = np.mean(arr) 
print(mean_arr)

# Calculate the standard deviation of the array
std_arr = np.std(arr) 
print(std_arr)

# Normalize the array
z_score = (arr - mean_arr) / std_arr
print(z_score)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7.5
4.6097722286464435
[[-1.62697843 -1.41004798 -1.19311752 -0.97618706]
 [-0.7592566  -0.54232614 -0.32539569 -0.10846523]
 [ 0.10846523  0.32539569  0.54232614  0.7592566 ]
 [ 0.97618706  1.19311752  1.41004798  1.62697843]]


In [11]:
response = askChatGPT("Write example python code that perform data normalization on fake data", max_tokens=1000)
print(response)



#Fake data
data = [1, 2, 3, 4, 5, 20]

#Normalization code
normalized_data = [(x - min(data)) / (max(data) - min(data)) for x in data]

#Print normalized data
print(normalized_data)

#Output
[0.0, 0.2, 0.4, 0.6, 0.8, 1.0]


In [12]:
response = askChatGPT("How do I select a time series model?", max_tokens=1000)
print(response)



When selecting a time series model, there are several factors to consider. The type of data, the complexity of the relationships in the data, the available computational resources, the expected accuracy of the model, and the desired application of the model should all be taken into account. Some common time series models are autoregressive integrated moving average (ARIMA), exponential smoothing, and Hidden Markov models (HMMs). Additionally, other machine learning models such as neural networks, support vector machines, and clustering may also be suitable for some time series applications.


### generating synthetic data

In [13]:
response = askChatGPT("Write example code that generates synthetic healthcare readmission data stored in a dataframe", max_tokens=1000)
print(response)



#importing necessary libraries
import pandas as pd
import numpy as np

#generating fake data
np.random.seed(10)
df = pd.DataFrame(np.random.randint(0,2,size=(15, 3)), columns=['Gender', 'Age', 'Readmission'])

#adding label to Ages
df['Age']=['<18','18-30','31-45','46-60','>60'] * 3

#adding label to Genders
df['Gender']=['Male','Female'] * 7

#shuffling data
df = df.sample(frac=1).reset_index(drop=True)

#printing dataframe
print(df)


In [14]:
import pandas as pd 
import numpy as np

# generating patient ids 
patient_ids = np.random.randint(1,10, size=5)
# generating readmission status (boolean)
readmission_status = np.random.choice([True, False], 5)
# generate readmission severity (1 - 5)
readmission_severity = np.random.randint(1,6, size=5)

data = {'Patient_ID': patient_ids ,
        'Readmission_Status': readmission_status,
        'Readmission_Severity': readmission_severity }

df = pd.DataFrame(data)
print(df)

   Patient_ID  Readmission_Status  Readmission_Severity
0           6               False                     4
1           8                True                     4
2           6                True                     3
3           4                True                     1
4           6               False                     1


In [15]:
response = askChatGPT("Write example code that generates synthetic healthcare readmission data stored in a dataframe. From this write code that builds a catboost model that predicts readmission outcomes. Also write code to calculate and print performance.", max_tokens=1000)
print(response)



# import necessary libraries 
import pandas as pd
import numpy as np 
import catboost as cb 

# generate synthetic healthcare readmission data stored in a dataframe  
data = [['Patient_1', 12, 'Male', 'Diabetes', 1], 
        ['Patient_2', 18, 'Female', 'Hypertension', 0],
        ['Patient_3', 35, 'Male', 'Obesity', 1], 
        ['Patient_4', 38, 'Male', 'Cubital Syndrome', 0],
        ['Patient_5', 56, 'Female', 'Hypertension', 0],
        ['Patient_6', 44, 'Female', 'Diabetes', 1],
        ['Patient_7', 23, 'Female', 'Obesity', 0],
        ['Patient_8', 22, 'Male', 'Cubital Syndrome', 0]] 
  
# Create the pandas DataFrame 
df_healthcare = pd.DataFrame(data, columns = ['Patient ID', 'Age', 'Gender', 'Condition', 'Readmission'], dtype = float)

# build a catboost model that predicts readmission outcomes 
features = ['Age', 'Gender', 'Condition']
X = df_healthcare[features]
y = df_healthcare["Readmission"]
data_pool = cb.Pool(X,y)
model = cb.CatBoostClassifier()
model.fit(data_pool)


In [16]:
# after some rectification of the chatgpt code
#importing libraries 
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier

def map_bool_to_int(x):
    if x == 'yes' or x == 'male':
        return 1
    elif x == 'no' or x == 'female':
        return 0

#generating synthetic readmission data
np.random.seed(123)
print(map(map_bool_to_int, np.random.choice(['male','female'],500)))
data = {
    'age': np.random.randint(18,90,500),
    'gender': map(map_bool_to_int, np.random.choice(['male','female'],500)),
    'medication': map(map_bool_to_int, np.random.choice(['yes','no'], 500)),
    'readmission': map(map_bool_to_int, np.random.choice(['yes','no'], 500))
    }
df = pd.DataFrame(data)

#building catboost model
X = df[['age','gender','medication']]
y = df['readmission']
model = CatBoostClassifier()
model.fit(X,y)

#calculating & printing performance
predictions = model.predict(X)
accuracy = sum(predictions == y)/len(y)
print('Model accuracy: ', accuracy)

Learning rate set to 0.007663
0:	learn: 0.6927425	total: 64.5ms	remaining: 1m 4s
1:	learn: 0.6922819	total: 65.9ms	remaining: 32.9s
2:	learn: 0.6918840	total: 66.7ms	remaining: 22.2s
3:	learn: 0.6914903	total: 67.4ms	remaining: 16.8s
4:	learn: 0.6911493	total: 68ms	remaining: 13.5s
5:	learn: 0.6907643	total: 68.6ms	remaining: 11.4s
6:	learn: 0.6907081	total: 69ms	remaining: 9.79s
7:	learn: 0.6903378	total: 69.5ms	remaining: 8.62s
8:	learn: 0.6902577	total: 69.9ms	remaining: 7.7s
9:	learn: 0.6898219	total: 70.5ms	remaining: 6.98s
10:	learn: 0.6894615	total: 71.1ms	remaining: 6.39s
11:	learn: 0.6890978	total: 71.8ms	remaining: 5.91s
12:	learn: 0.6887073	total: 72.3ms	remaining: 5.49s
13:	learn: 0.6885319	total: 72.8ms	remaining: 5.12s
14:	learn: 0.6884011	total: 73.1ms	remaining: 4.8s
15:	learn: 0.6881821	total: 73.5ms	remaining: 4.52s
16:	learn: 0.6879056	total: 73.9ms	remaining: 4.27s
17:	learn: 0.6875446	total: 74.3ms	remaining: 4.05s
18:	learn: 0.6871716	total: 74.8ms	remaining: 3.86

In [17]:
response = askChatGPT("Write example python code that generates synthetic transaction data stored in a dataframe", max_tokens=1000)
print(response)



#import dataframe
import pandas as pd 

# create an empty dataframe
transaction_df = pd.DataFrame()

# add columns
transaction_df['merchant'] = ['Amazon', 'Target', 'Walmart', 'McDonalds', 'Starbucks']
transaction_df['amount'] = [50, 25, 10, 14.95, 5.50]
transaction_df['date'] = ['2020-05-14', '2020-04-01', '2020-04-20', '2020-03-03', '2020-02-13']

#print dataframe
print(transaction_df)


In [18]:
import pandas as pd
import numpy as np

# Create empty dataframe
df = pd.DataFrame()

# Add columns
df['CustomerName'] = ["John Doe", "Jane Doe", "Joseph Doe"]
df['Amount'] = np.random.randint(20, 200, size=(3,))
df['Category'] = ['Groceries', 'Travel', 'Food']
df['Transaction Date'] = ['05/01/20', '06/01/20','07/01/20']

# Print the dataframe
print(df)

  CustomerName  Amount   Category Transaction Date
0     John Doe     114  Groceries         05/01/20
1     Jane Doe     113     Travel         06/01/20
2   Joseph Doe     124       Food         07/01/20


In [19]:
response = askChatGPT("Write example python code that generates synthetic transaction data stored in a dataframe. Includes customer ID, CustomerName, Amount, Category, Age, Gender, and zip code", max_tokens=1000)
print(response)



import pandas as pd
import numpy as np

# create columns 
data_columns = ["CustomerID", "CustomerName", "Amount", "Category", "Age", "Gender", "Zip"]
# create dataframe
df = pd.DataFrame(columns=data_columns)

# generate 1000 customers
for i in range(1000):
    # generate and add customer ID
    df.loc[i, "CustomerID"] = "CUS_" + str(i)
    # generate and add customer name
    df.loc[i, "CustomerName"] = "Customer " + str(i)
    # generate and add a random amount
    df.loc[i, "Amount"] = np.random.randint(1,1000)
    # generate and add a category
    df.loc[i, "Category"] = np.random.choice(["food", "clothing", "home", "electronics", "furniture"])
    # generate and add age
    df.loc[i, "Age"] = np.random.randint(18, 65)
    # generate and add gender
    df.loc[i, "Gender"] = np.random.choice(["Male", "Female"])
    # generate and add zip code
    df.loc[i, "Zip"] = np.random.randint(1000, 9999)
    
df.head()


In [20]:
# running after some minor correction of code
import pandas as pd
import random

# generate customerIds
customerIds = [random.randint(1000, 10000) for x in range(10)]

# generate names
names = ["John", "Sara", "Mathew", "Graham", "Kris", "Chris", "Karen", "Olivia",
         "Jack", "Emily"]

# generate amounts
amounts = [random.randint(100, 2000) for x in range(10)]

# generate categories
categories = ["Grocery", "Home Improvement",
              "Electronics", "Furniture", "Gas", "Travel", "Clothing", "Kids", "Books", "Pens"]

# generate age
ages = [random.randint(18, 70) for x in range(10)]

# generate gender
gender = np.random.choice(["M", "F"], 10)

# generate zipcode
zipCodes = [random.randint(10001, 11001) for x in range(10)]
print(len(names), len(amounts), len(categories), len(ages), len(gender), len(zipCodes))
# create dictionary
d = { "customerId": customerIds,
      "CustomerName": names,
      "Amount": amounts,
      "Category": categories,
      "Age": ages,
      "Gender": gender,
      "ZipCode": zipCodes
    }

# create dataframe
df = pd.DataFrame(data=d)

# print df
print(df)

10 10 10 10 10 10
   customerId CustomerName  Amount          Category  Age Gender  ZipCode
0        4459         John     330           Grocery   68      F    10719
1        6978         Sara     755  Home Improvement   41      F    10453
2        6908       Mathew     729       Electronics   35      M    10318
3        9045       Graham    1984         Furniture   50      F    10736
4        8907         Kris    1474               Gas   55      F    10773
5        3879        Chris    1239            Travel   50      M    10442
6        7609        Karen     685          Clothing   67      F    10359
7        5797       Olivia     187              Kids   62      F    10559
8        1295         Jack     798             Books   47      M    10264
9        9418        Emily     863              Pens   58      F    10591


In [21]:
response = askChatGPT("List some good public datasets", max_tokens=1000)
print(response)



1. Kaggle Datasets - https://www.kaggle.com/datasets
2. Google BigQuery Public Datasets - https://cloud.google.com/bigquery/public-data
3. Amazon Web Services Public Datasets - https://aws.amazon.com/public-datasets/
4. Census Data - https://www.census.gov/data
5. World Bank Data - https://datacatalog.worldbank.org/
6. ProPublica Data Store - https://www.propublica.org/datastore/
7. Five Thirty Eight - https://data.fivethirtyeight.com/
8. US Government Open Data - https://www.data.gov/
9. Open Football Data - http://openfooty.org/data
10. Awesome Public Datasets - https://github.com/awesomedata/awesome-public-datasets


In [22]:
response = askChatGPT("What are some emergning machine learning use-cases in healthcare?", max_tokens=1000)
print(response)



1. Smart Medical Imaging: Machine learning is already being used in medical imaging to detect abnormalities, detect cancer and diagnose diseases more accurately and quickly.

2. Automated Diagnosis: AI-based tools are being developed and implemented to assist doctors in making more accurate and faster diagnoses.

3. Clinical Decision Support: Machine learning can be used to help healthcare professionals make better decisions and provide better care, by mining large amounts of patient data and suggesting suitable treatment pathways and medications.

4. Enhanced Medical Records: Machine learning algorithms are being used to analyze large amounts of data and structure medical records to provide better insights into patient health and history. 

5. Robot-Assisted Surgery: Robot-assisted surgery can be used to assist with various types of surgeries, reducing the time taken to perform them and increasing the accuracy.

6. Drug Discovery and Development: Machine learning is being used to de

In [23]:
response = askChatGPT("Write a supervisor machine learning example code", max_tokens=1000)
print(response)



import numpy as np
from sklearn import datasets

#Load the iris dataset 
iris = datasets.load_iris() 

#Split into training and test sets 
X = iris.data #features
y = iris.target #labels 

#Split the dataset into training set (75%) and test set (25%)
s = np.random.permutation(len(X))
X_train, X_test = X[s][:75], X[s][75:]
y_train, y_test = y[s][:75], y[s][75:]

#Create the Supervised Learning Model
#We'll use Random Forest Classification to predict the labels
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=50) 

#Train the model
#Pass the training set features and labels to the classifier
clf.fit(X_train, y_train)

#Test the model
#Test the model on the unseen test set 
clf.predict(X_test)

#Calculate the accuracy of the Model
#Calculate the accuracy of the model using the test set labels
score=clf.score(X_test, y_test) 
print("Accuracy of the Supervised Learning Model : ",score)


In [24]:
# after correction
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets

iris = datasets.load_iris()

#Load data into a variable
X_train, y_train, X_test, y_test = get_data()

#Initialize RandomForestClassifier
clf = RandomForestClassifier(random_state=0)

#Fit the model
clf.fit(X_train, y_train)

#Make predictions
y_pred = clf.predict(X_test)

#Evaluate accuracy of model
accuracy = accuracy_score(y_test, y_pred)

#Use supervised learning techniques to get further insights into the data
#Continuously measure performance
clf.score(X_test, y_test)

#Identifying feature importance
f_importance = list(zip(X_train, clf.feature_importances_))

#Make hyperparameter optimization to find best parameters
clf.best_estimator_

NameError: name 'get_data' is not defined